name: Test
on: [pull_request]
jobs:
  test:
    name: Test
    strategy:
      matrix:
        platform: [macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Set up Go 1.17
      uses: actions/setup-go@v1
      with:
        go-version: 1.17.6
      id: go
    - name: configure Pagefile
      uses: al-cheb/configure-pagefile-action@v1.2
      with:
        minimum-size: 16GB
        maximum-size: 16GB
        disk-root: "C:"
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build
      run: make GOFLAGS="-tags=netgo,nodocker" BUILD_IN_CONTAINER=false cmd/agent/agent cmd/agentctl/agentctl cmd/agent-operator/agent-operator
    - name: Test
      run: make GOFLAGS="-tags=netgo,nodocker" BUILD_IN_CONTAINER=false test
